In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
import xgboost as xgb

In [86]:
data = pd.read_csv("usage_by_weather2.csv")
data.drop(columns = ['Unnamed: 0'])

,year,month,day,temp,cloud,rainfall_total,Humidity_mean,solar,customer,wh,kwh
0,2021,1,1,-0.6,7.3,0.0,83.1,9.00,783260,49968118.15,11154070.87
1,2021,1,2,-0.3,3.8,0.5,67.8,12.54,783281,43576388.06,10820313.94
2,2021,1,3,-0.6,7.3,0.0,54.6,10.37,783288,44345831.21,10577876.27
3,2021,1,4,1.2,3.1,0.0,71.8,10.07,783288,49666971.53,11410542.58
4,2021,1,5,-0.2,8.0,0.0,64.9,7.74,783310,44114435.78,11097614.74
...,...,...,...,...,...,...,...,...,...,...,...
725,2022,12,27,0.3,1.8,0.0,74.1,13.08,800308,31743683.54,9442942.40
726,2022,12,28,-0.2,5.3,0.0,75.4,9.62,802036,32641190.23,9679363.18
727,2022,12,29,0.7,2.1,0.0,63.3,12.25,803784,58820056.15,11754265.48
728,2022,12,30,1.0,6.3,0.0,70.4,9.25,805066,52733978.57,12149583.10
729,2022,12,31,1.4,1.4,0.0,66.1,12.02,805564,44225974.10,11472992.97

In [5]:
# Convert date to datetime object and extract features
data["date"] = pd.to_datetime(data[['year', 'month', 'day']])
data["day_of_week"] = data["date"].dt.dayofweek

# Drop the date-related columns
data = data.drop(["year", "month", "day"], axis=1)

# Define features and target
features = data.drop("kwh", axis=1)
target = data["kwh"]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train the XGBoost model
model = xgb.XGBRegressor(objective ='reg:squarederror', n_estimators=1000, learning_rate=0.05, max_depth=5)
model.fit(X_train, y_train)

# Predict and evaluate the model
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred

SyntaxError: unexpected EOF while parsing (687464235.py, line 27)

In [ ]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# load the historical data
df = data

# select the relevant columns for the model
X = df[['year', 'month', 'day', 'temp', 'cloud', 'rainfall_total', 'Humidity_mean', 'solar']]
y = df[['kwh']]

# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# define the XGBoost model
model = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 100)

# train the model
model.fit(X_train, y_train)

# make predictions on the test set
y_pred = model.predict(X_test)

# evaluate the model performance
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print('RMSE:', rmse)

# use the model to predict power consumption for January 1st to March 31st, 2023
future_data = pd.DataFrame({'year': [2023]*90, 'month': list(range(1,4))*30, 'day': list(range(1,31))*3, 
                            'temp': [25]*90, 'cloud': [50]*90, 'rainfall_total': [100]*90, 
                            'Humidity_mean': [70]*90, 'solar': [50]*90})
y_pred_future = model.predict(future_data)

# print the predicted power consumption for each day from January 1st to March 31st, 2023
print('Predicted power consumption for Jan 1 - Mar 31, 2023:')
print(y_pred_future)

RMSE: 26899821.645889036
Predicted power consumption for Jan 1 - Mar 31, 2023:
[12013102. 13594422. 14693482. 12532418. 13654472. 14301008. 12613388.
 14481820. 14993651. 13535955. 14680431. 15335505. 13627911. 14939601.
 15360738. 13709123. 15278103. 16623519. 13632211. 14578873. 16023983.
 13349587. 14150633. 15297239. 13274700. 14359910. 14774882. 13304285.
 14572308. 14606411. 12013102. 13594422. 14693482. 12532418. 13654472.
 14301008. 12613388. 14481820. 14993651. 13535955. 14680431. 15335505.
 13627911. 14939601. 15360738. 13709123. 15278103. 16623519. 13632211.
 14578873. 16023983. 13349587. 14150633. 15297239. 13274700. 14359910.
 14774882. 13304285. 14572308. 14606411. 12013102. 13594422. 14693482.
 12532418. 13654472. 14301008. 12613388. 14481820. 14993651. 13535955.
 14680431. 15335505. 13627911. 14939601. 15360738. 13709123. 15278103.
 16623519. 13632211. 14578873. 16023983. 13349587. 14150633. 15297239.
 13274700. 14359910. 14774882. 13304285. 14572308. 14606411.]

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import xgboost as xgb

# Load the dataset
data = data

# Convert date to datetime object and extract features
data["date"] = pd.to_datetime(data[['year', 'month', 'day']])
data["day_of_week"] = data["date"].dt.dayofweek

# Drop the date-related columns
data = data.drop(["year", "month", "day"], axis=1)

# Define features and target
features = data.drop("wh", axis=1)
target = data["wh"]

# Split data into training and evaluation sets
train_data = data[data["date"] <= "2022-08-31"]
eval_data = data[(data["date"] >= "2022-09-01") & (data["date"] <= "2022-12-31")]

X_train = train_data.drop(["date", "wh"], axis=1)
y_train = train_data["wh"]
X_eval = eval_data.drop(["date", "wh"], axis=1)
y_eval = eval_data["wh"]

# Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform

In [ ]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.model_selection import train_test_split

In [ ]:
data = pd.read_csv("usage_by_weather2.csv")
data.drop(columns = ['Unnamed: 0'])

In [87]:
data = pd.read_csv("usage_by_weather2.csv")
data_lin = data.drop(columns = ['wh', 'Unnamed: 0'])
data_lin

,year,month,day,temp,cloud,rainfall_total,Humidity_mean,solar,customer,kwh
0,2021,1,1,-0.6,7.3,0.0,83.1,9.00,783260,11154070.87
1,2021,1,2,-0.3,3.8,0.5,67.8,12.54,783281,10820313.94
2,2021,1,3,-0.6,7.3,0.0,54.6,10.37,783288,10577876.27
3,2021,1,4,1.2,3.1,0.0,71.8,10.07,783288,11410542.58
4,2021,1,5,-0.2,8.0,0.0,64.9,7.74,783310,11097614.74
...,...,...,...,...,...,...,...,...,...,...
725,2022,12,27,0.3,1.8,0.0,74.1,13.08,800308,9442942.40
726,2022,12,28,-0.2,5.3,0.0,75.4,9.62,802036,9679363.18
727,2022,12,29,0.7,2.1,0.0,63.3,12.25,803784,11754265.48
728,2022,12,30,1.0,6.3,0.0,70.4,9.25,805066,12149583.10
729,2022,12,31,1.4,1.4,0.0,66.1,12.02,805564,11472992.97

In [15]:
def get_rmse(model):
    from sklearn.metrics import mean_squared_error
    pred = model.predict(X_test)
    mse = mean_squared_error(y_test,pred)
    rmse = np.sqrt(mse)
    print(model.__class__.__name__,' 로그 변환된 RMSE : ',rmse)
    return rmse

def get_rmses(models):
    rmses = []
    for model in models:
        rmse = get_rmse(model) 
        rmses.append(rmse)
    return rmses

In [16]:
y = data_lin['wh'] 
X = data_lin.drop(columns=['wh'])
X_train,X_test,y_train,y_test = train_test_split(X,
                                                 y,
                                                 test_size=0.2,
                                                 random_state=156)
lr_reg = LinearRegression()
lr_reg.fit(X_train,y_train)
ridge_reg = Ridge()
ridge_reg.fit(X_train,y_train)
lasso_reg = Lasso()
lasso_reg.fit(X_train,y_train)

models = [lr_reg,ridge_reg,lasso_reg]
get_rmses(models)

LinearRegression  로그 변환된 RMSE :  209475898.75777933
Ridge  로그 변환된 RMSE :  210205752.89107838
Lasso  로그 변환된 RMSE :  210197526.9104199

c:\Users\admin\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.772e+20, tolerance: 9.622e+16
  model = cd_fast.enet_coordinate_descent(

[209475898.75777933, 210205752.89107838, 210197526.9104199]

In [22]:
from sklearn.linear_model import Ridge

In [23]:
ridge_model = Ridge(alpha=1.0)


X_train = data_lin['year', 'month', 'day', 'temp', 'cloud', 'rainfall_total', 'Humidity_mean', 'solar', 'customer']
y_train = ['wh']


ridge_model.fit(X_train, y_train)
y_pred = ridge_model.predict(X_test)

KeyError: ('year', 'month', 'day', 'temp', 'cloud', 'rainfall_total', 'Humidity_mean', 'solar', 'customer')

In [25]:
data_lin.columns

Index(['Unnamed: 0', 'year', 'month', 'day', 'temp', 'cloud', 'rainfall_total',
       'Humidity_mean', 'solar', 'customer', 'wh'],
      dtype='object')

In [83]:
data_lin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            730 non-null    int64
 1   month           730 non-null    int64
 2   day             730 non-null    int64
 3   temp            730 non-null    float64
 4   cloud           730 non-null    float64
 5   rainfall_total  730 non-null    float64
 6   Humidity_mean   730 non-null    float64
 7   solar           730 non-null    float64
 8   customer        730 non-null    int64
 9   kwh             730 non-null    float64
dtypes: float64(6), int64(4)
memory usage: 57.2 KB

In [92]:
data = pd.read_csv("usage_by_weather2.csv")
data_lin = data.drop(columns = ['wh', 'Unnamed: 0'])
data_lin

,year,month,day,temp,cloud,rainfall_total,Humidity_mean,solar,customer,kwh
0,2021,1,1,-0.6,7.3,0.0,83.1,9.00,783260,11154070.87
1,2021,1,2,-0.3,3.8,0.5,67.8,12.54,783281,10820313.94
2,2021,1,3,-0.6,7.3,0.0,54.6,10.37,783288,10577876.27
3,2021,1,4,1.2,3.1,0.0,71.8,10.07,783288,11410542.58
4,2021,1,5,-0.2,8.0,0.0,64.9,7.74,783310,11097614.74
...,...,...,...,...,...,...,...,...,...,...
725,2022,12,27,0.3,1.8,0.0,74.1,13.08,800308,9442942.40
726,2022,12,28,-0.2,5.3,0.0,75.4,9.62,802036,9679363.18
727,2022,12,29,0.7,2.1,0.0,63.3,12.25,803784,11754265.48
728,2022,12,30,1.0,6.3,0.0,70.4,9.25,805066,12149583.10
729,2022,12,31,1.4,1.4,0.0,66.1,12.02,805564,11472992.97

In [97]:
# data_lin['date'] = str(data_lin['year']) + "-" + str(data_lin['month']) + "-" + str(data_lin['day'])
str(data_lin['year']).replace("\n", '')

0      20211      20212      20213      20214      2021       ... 725    2022726    2022727    2022728    2022729    2022Name: year, Length: 730, dtype: int64

In [89]:
data_lin

,year,month,day,temp,cloud,rainfall_total,Humidity_mean,solar,customer,kwh
0,2021,1,1,-0.6,7.3,0.0,83.1,9.00,783260,11154070.87
1,2021,1,2,-0.3,3.8,0.5,67.8,12.54,783281,10820313.94
2,2021,1,3,-0.6,7.3,0.0,54.6,10.37,783288,10577876.27
3,2021,1,4,1.2,3.1,0.0,71.8,10.07,783288,11410542.58
4,2021,1,5,-0.2,8.0,0.0,64.9,7.74,783310,11097614.74
...,...,...,...,...,...,...,...,...,...,...
725,2022,12,27,0.3,1.8,0.0,74.1,13.08,800308,9442942.40
726,2022,12,28,-0.2,5.3,0.0,75.4,9.62,802036,9679363.18
727,2022,12,29,0.7,2.1,0.0,63.3,12.25,803784,11754265.48
728,2022,12,30,1.0,6.3,0.0,70.4,9.25,805066,12149583.10
729,2022,12,31,1.4,1.4,0.0,66.1,12.02,805564,11472992.97

___Ridge 모델___

In [134]:
def Ridge(data):

    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import Ridge
    from sklearn.metrics import mean_squared_error

    # 훈련 세트와 테스트 세트로 분할
    X = data[['year', 'month', 'day', 'temp', 'cloud', 'rainfall_total', 'Humidity_mean', 'solar', 'customer']]
    y = data['kwh']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

    # alpha값이 1.0인 Ridge 모델 생성
    ridge_model = Ridge(alpha = 1)

    # 데이터에 모델 적용
    ridge_model.fit(X_train, y_train)

    # 예측
    y_pred = ridge_model.predict(X_test)

    # 오차**2 계산
    mse = mean_squared_error(y_test, y_pred)

    return format(mse)
    # print("Ridge  학습 점수 : ", format(Ridge.score(X_train, y_train)))
    # print("Ridge  테스트 점수 : ", format(Ridge.score(X_test, y_test)))


result = []
for i in range(0, 50):
    result = result.append(Ridge(data_lin))

result_df = pd.DataFrame({'오차':[result]})
result_df

AttributeError: 'NoneType' object has no attribute 'append'

___Lasso 모델___

In [74]:
def Lasso(data):
    
    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import Lasso
    from sklearn.metrics import mean_squared_error

    X = data[['year', 'month', 'day', 'temp', 'cloud', 'rainfall_total', 'Humidity_mean', 'solar', 'customer']]
    y = data['kwh']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    lasso_model = Lasso(alpha = 0.01)

    lasso_model.fit(X_train, y_train)

    y_pred = lasso_model.predict(X_test)

    mse = mean_squared_error(y_test, y_pred)

    print("Lasso  평균제곱 오차 :", mse)

In [75]:
def LinearRegression(data):
    
    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import LinearRegression
    from sklearn.metrics import mean_squared_error

    X = data[['year', 'month', 'day', 'temp', 'cloud', 'rainfall_total', 'Humidity_mean', 'solar', 'customer']]
    y = data['kwh']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Create a Linear Regression model
    lr_model = LinearRegression()

    # Fit the model to the training data
    lr_model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = lr_model.predict(X_test)

    # Calculate the mean squared error of the predictions
    mse = mean_squared_error(y_test, y_pred)

    print("Linear 평균제곱 오차 :", mse)

In [76]:
Ridge(data_lin)
Lasso(data_lin)
# LinearRegression(data_lin)

Ridge  평균제곱 오차 : 715752327275362.2
Lasso  평균제곱 오차 : 715752828954137.1

___왜 안될까___

In [108]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error


def Ridge(data):
    X = data[['year', 'month', 'day', 'temp', 'cloud',
              'rainfall_total', 'Humidity_mean', 'solar', 'customer']]
    y = data['kwh']
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42)
    ridge_model = Ridge(alpha = 10)
    ridge_model.fit(X_train, y_train)
    mse = mean_squared_error(y_test, ridge_model.predict(X_test))
    print("Ridge 평균제곱 오차: {:.2f}".format(mse))
    print("Ridge 학습 점수: {:.2f}".format(ridge_model.score(X_train, y_train)))
    print("Ridge 테스트 점수: {:.2f}".format(ridge_model.score(X_test, y_test)))

Ridge(data_lin)

TypeError: Ridge() got an unexpected keyword argument 'alpha'